# curl localhost:8080/time
GET localhost:8080/time

###

GET localhost:8080/person
Accept: application/xml

###

GET localhost:8080/person
Accept: application/json

###

GET localhost:8080/person
Accept: text/plain

###

GET localhost:8080/person/zk
Accept: text/plain

###

GET localhost:8080/person/zk
Accept: application/xml

###

GET localhost:8080/person/json
Accept: application/json

###

GET localhost:8080/person/response
Accept: application/json


###
POST http://0.0.0.0:8080/person/cnt

###
PUT http://0.0.0.0:8080/person/cool
Content-Type: application/json

{
  "name": "Thomas :)"
}

###

POST http://0.0.0.0:8080/person/jsontype
Content-Type: application/json

{
  "vorname": "Markus",
  "nachname": "H"
}

###

POST http://0.0.0.0:8080/person/jsontype
Content-Type: application/json

[
  {
    "vorname": "Gerald",
    "nachname": "K"
  },
  {
    "vorname": "Riccarda",
    "nachname": "R"
  }
]

###

POST http://0.0.0.0:8080/person
Content-Type: application/json

{
"name": "Horst"
}



